# Generated by Django 4.2.16 on 2024-12-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_food_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
